### ISSUE TITLE
Create 2.2.1 release

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#960]
This is effectively to keep track of what will be in 2.2.1:

- [x] 0de92f1: Fix for #957
- [x] c1fb0aa030e7af3380e6526dc7318e0026fa9be2: Fix for #979
- [x] f78a32abeb5d36a2dbbc950a2133089f8e0dca1f: Fix for #981
- [x] 33c5f4acd132dc0b2058607e62f73c2b2ec3b68a: Fix for #971

**Comment by jskeet** [comment]
If we address #979 by adding serialization of `DateTimeZone` as a new feature and release 2.3.0 (with a corresponding NodaTime.Serialization.JsonNet release), do we still need a 2.2.1?

**Comment by jskeet** [comment]
Released 2017-10-14.
